version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  # @todo the recaptcha values should be removed (?) once contact-us is moved to core.
  RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY-(unset)}
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY-(unset)}
  # @todo the sendgrid values should be removed once the @base-cms/mailer service is created.
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: basecmsdev@gmail.com
  YARN_CACHE_FOLDER: /.yarn-cache

x-env-leonis: &env-leonis
  GRAPHQL_URI: ${GRAPHQL_URI-https://leonis.graphql.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://leonis.oembed.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://leonis.rss.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://leonis.sitemaps.base.parameter1.com}

x-env-tauron: &env-tauron
  GRAPHQL_URI: ${GRAPHQL_URI-https://tauron.graphql.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://tauron.oembed.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://tauron.rss.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://tauron.sitemaps.base.parameter1.com}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.tauron.base.parameter1.com/graphql}

x-env-development: &env-development
  GRAPHQL_URI: ${GRAPHQL_URI-http://host.docker.internal:10002}
  OEMBED_URI: ${OEMBED_URI-http://host.docker.internal:10013}
  RSS_URI: ${RSS_URI-http://host.docker.internal:10011}
  SITEMAPS_URI: ${SITEMAPS_URI-http://host.docker.internal:10009}

x-site-command: &site-cmd
  entrypoint: ["node_modules/.bin/basecms-website"]
  command: ["dev", "index.js"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  hh:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/hearthubs.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9810
      LIVERELOAD_PORT: 19810
      TENANT_KEY: ascend_hh
      SITE_ID: 5e79147a9610c96162e3a0bc
    ports:
      - "9810:80"
      - "19810:19810"

  qcor:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/qcor.hub.heart.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9811
      LIVERELOAD_PORT: 19811
      TENANT_KEY: ascend_hh
      SITE_ID: 5f09f138c6eb965e078b4568
    ports:
      - "9811:80"
      - "19811:19811"

  bcvs:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/bcvs.hub.heart.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9812
      LIVERELOAD_PORT: 19812
      TENANT_KEY: ascend_hh
      SITE_ID: 5f09c343c6eb96c0068b4573
    ports:
      - "9812:80"
      - "19812:19812"

  vasculardiscovery:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/vasculardiscovery.hub.heart.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9813
      LIVERELOAD_PORT: 19813
      TENANT_KEY: ascend_hh
      SITE_ID: 5f09f15dc6eb965f078b456f
    ports:
      - "9813:80"
      - "19813:19813"

  hypertension:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/hypertension.hub.heart.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9814
      LIVERELOAD_PORT: 19814
      TENANT_KEY: ascend_hh
      SITE_ID: 5f09c37bc6eb96a9058b4579
    ports:
      - "9814:80"
      - "19814:19814"

  minexpo:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/minexpo.com
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9815
      LIVERELOAD_PORT: 19815
      ALGOLIA_API_KEY: ${ALGOLIA_API_KEY}
      ALGOLIA_APP_ID: ${ALGOLIA_APP_ID}
      ALGOLIA_DEFAULT_INDEX: ${ALGOLIA_DEFAULT_INDEX}
      TENANT_KEY: ascend_minex
      SITE_ID: 5f2c4e7900d6f47b4ca70040
    ports:
      - "9815:80"
      - "19815:19815"

  sessions:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/sessions.hub.heart.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9816
      LIVERELOAD_PORT: 19816
      TENANT_KEY: ascend_hh
      SITE_ID: 5f69318496e7bf68228b4597
    ports:
      - "9816:80"
      - "19816:19816"

  imex:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/imex.ascendmedia.com
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9817
      LIVERELOAD_PORT: 19817
      TENANT_KEY: ascend_hh
      SITE_ID: 5f69316296e7bf68228b4595
    ports:
      - "9817:80"
      - "19817:19817"

  isc:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/isc.hub.heart.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9818
      LIVERELOAD_PORT: 19818
      TENANT_KEY: ascend_hh
      SITE_ID: 5fa07807adb660cb238b45a9
    ports:
      - "9818:80"
      - "19818:19818"

  bulletin:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/bulletin.entnet.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9919
      LIVERELOAD_PORT: 19919
      TENANT_KEY: ascend_hh
      SITE_ID: 6001de6ce8e95f05158b4577
    ports:
      - "9919:80"
      - "19919:19919"

  aua:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/auadailynews.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9920
      LIVERELOAD_PORT: 19920
      TENANT_KEY: ascend_hh
      SITE_ID: 60747a8880a4312e028b45d6
    ports:
      - "9920:80"
      - "19920:19920"

  aad:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/aadmeetingnews.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9921
      LIVERELOAD_PORT: 19921
      TENANT_KEY: ascend_hh
      SITE_ID: 60c7666d46f24a64538b458d
    ports:
      - "9921:80"
      - "19921:19921"

  template:
    <<: *node
    <<: *site-cmd
    working_dir: /root/sites/examplesite.org
    environment:
      <<: *env
      <<: *env-tauron
      PORT: 80
      EXPOSED_PORT: 9999
      LIVERELOAD_PORT: 19999
      TENANT_KEY: ascend_hh
      SITE_ID: 60c7666d46f24a64538b458d
    ports:
      - "9999:80"
      - "19999:19999"
