name: Deploy sites (production)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - id: tag_version
      run: |
        REF=$(echo $GITHUB_REF | cut -d / -f 3)
        [[ "$GITHUB_REF" =~ ^refs/tags.*$ ]] && VERSION="$REF" || VERSION="${REF}-${GITHUB_SHA::7}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.tag_version.outputs.version }}

  notify-start:
    needs: [version]
    uses: parameter1/actions/.github/workflows/notify-start.yml@main
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}

  post-deploy-failure:
    if: failure()
    needs: [notify-start, deploy-sites]
    uses: parameter1/actions/.github/workflows/notify-fail.yml@main
    secrets: inherit
    with:
      slack-thread: ${{ needs.notify-start.outputs.slack-thread }}

  post-deploy-complete:
    if: success()
    needs: [notify-start, deploy-sites]
    uses: parameter1/actions/.github/workflows/notify-complete.yml@main
    secrets: inherit
    with:
      slack-thread: ${{ needs.notify-start.outputs.slack-thread }}

  ######################
  # Add websites here! #
  ######################

  build-sites:
    needs: [version]
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 60c7666d46f24a64538b458d, dir: aadmeetingnews.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-aadmeetingnews.org }
          - { id: 611bb90b0fa7e3b2258b458c, dir: aao.hns.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-aao.hns.org }
          - { id: 611a92384931c530198b45bf, dir: acep.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-acep.org }
          - { id: 62f156eeb42f9308288b45e8, dir: ampulmonary.com, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-ampulmonary.com }
          - { id: 611a7eaf3fdb1225198b45a3, dir: asa.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-asa.org }
          - { id: 611bbf5d4c3ae90e268b4592, dir: ashp.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-ashp.org }
          - { id: 60747a8880a4312e028b45d6, dir: auadailynews.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-auadailynews.org }
          - { id: 5f09c343c6eb96c0068b4573, dir: bcvs.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-bcvs.hub.heart.org }
          - { id: 6001de6ce8e95f05158b4577, dir: bulletin.entnet.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-bulletin.entnet.org }
          - { id: 60c7666d46f24a64538b458d, dir: examplesite.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-examplesite.org }
          - { id: 5e79147a9610c96162e3a0bc, dir: hearthubs.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-hearthubs.org }
          - { id: 5f09c37bc6eb96a9058b4579, dir: hypertension.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-hypertension.hub.heart.org }
          - { id: 5f69316296e7bf68228b4595, dir: imex.ascendmedia.com, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-imex.ascendmedia.com }
          - { id: 6228b5a440412800498b456f, dir: imexfrankfurt.ascendmedia.com, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-imexfrankfurt.ascendmedia.com }
          - { id: 5fa07807adb660cb238b45a9, dir: isc.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-isc.hub.heart.org }
          - { id: 5f2c4e7900d6f47b4ca70040, dir: minexpo.com, stack: tauron, account: ascend, tenant: ascend_minex, rancher_label: ascend-media-minexpo.com }
          - { id: 5f09f138c6eb965e078b4568, dir: qcor.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-qcor.hub.heart.org }
          - { id: 5f69318496e7bf68228b4597, dir: sessions.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-sessions.hub.heart.org }
          - { id: 616db80fb973b9f0308b45aa, dir: shm.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-shm.org }
          - { id: 5f09f15dc6eb965f078b456f, dir: vasculardiscovery.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-vasculardiscovery.hub.heart.org }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
      docker_image: ${{ vars.AWS_ECR_REGISTRY }}/base-cms-websites:${{ matrix.site.account }}-${{ matrix.site.dir }}-${{ needs.version.outputs.version }}
      site_id: ${{ matrix.site.id }}
      site_host: ${{ matrix.site.dir }}
      infra_stack: ${{ matrix.site.stack }}
      tenant_key: ${{ matrix.tenant }}
      push: true
    secrets: inherit

  deploy-sites:
    needs: [version, build-sites]
    uses: parameter1/actions/.github/workflows/website-deploy-production.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 60c7666d46f24a64538b458d, dir: aadmeetingnews.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-aadmeetingnews.org }
          - { id: 611bb90b0fa7e3b2258b458c, dir: aao.hns.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-aao.hns.org }
          - { id: 611a92384931c530198b45bf, dir: acep.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-acep.org }
          - { id: 62f156eeb42f9308288b45e8, dir: ampulmonary.com, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-ampulmonary.com }
          - { id: 611a7eaf3fdb1225198b45a3, dir: asa.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-asa.org }
          - { id: 611bbf5d4c3ae90e268b4592, dir: ashp.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-ashp.org }
          - { id: 60747a8880a4312e028b45d6, dir: auadailynews.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-auadailynews.org }
          - { id: 5f09c343c6eb96c0068b4573, dir: bcvs.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-bcvs.hub.heart.org }
          - { id: 6001de6ce8e95f05158b4577, dir: bulletin.entnet.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-bulletin.entnet.org }
          - { id: 60c7666d46f24a64538b458d, dir: examplesite.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-examplesite.org }
          - { id: 5e79147a9610c96162e3a0bc, dir: hearthubs.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-hearthubs.org }
          - { id: 5f09c37bc6eb96a9058b4579, dir: hypertension.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-hypertension.hub.heart.org }
          - { id: 5f69316296e7bf68228b4595, dir: imex.ascendmedia.com, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-imex.ascendmedia.com }
          - { id: 6228b5a440412800498b456f, dir: imexfrankfurt.ascendmedia.com, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-imexfrankfurt.ascendmedia.com }
          - { id: 5fa07807adb660cb238b45a9, dir: isc.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-isc.hub.heart.org }
          - { id: 5f2c4e7900d6f47b4ca70040, dir: minexpo.com, stack: tauron, account: ascend, tenant: ascend_minex, rancher_label: ascend-media-minexpo.com }
          - { id: 5f09f138c6eb965e078b4568, dir: qcor.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-qcor.hub.heart.org }
          - { id: 5f69318496e7bf68228b4597, dir: sessions.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-sessions.hub.heart.org }
          - { id: 616db80fb973b9f0308b45aa, dir: shm.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-shm.org }
          - { id: 5f09f15dc6eb965f078b456f, dir: vasculardiscovery.hub.heart.org, stack: tauron, account: ascend, tenant: ascend_hh, rancher_label: ascend-media-vasculardiscovery.hub.heart.org }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      docker_image: ${{ vars.AWS_ECR_REGISTRY }}/base-cms-websites:${{ matrix.site.account }}-${{ matrix.site.dir }}-${{ needs.version.outputs.version }}
      infra_stack: ${{ matrix.site.stack }}
      rancher_label_key: basecms-website
      rancher_label_val: ${{ matrix.site.rancher_label }}
    secrets: inherit
